/cx_front/lslidar_driver_node:
  ros__parameters:
    packet_rate: 1695.0
    device_ip: 192.168.1.203  # Lidar IP
    msop_port: 2374           # Lidar data port
    difop_port: 2375          # Lidar device port
    pcl_type: false           # Point cloud type true: xyzi
    add_multicast: false      # Whether the lidar uses multicast mode true: use multicast mode
    group_ip: 224.1.1.2       # Multicast IP
    use_time_service: false   # Whether the lidar uses external time service (GPS PTP NTP) true: use external time service
    min_range: 0.15           # Minimum lidar scan distance (points less than this value will be filtered)
    max_range: 200.0          # Maximum lidar scan distance (points greater than this value will be filtered)
    angle_disable_min: 0      # Minimum angle clipping for lidar scan, unit 0.01°
    angle_disable_max: 0      # Maximum angle clipping for lidar scan, unit 0.01°
    distance_unit: 0.4
    horizontal_angle_resolution: 0.18     # 10Hz: 0.18  20Hz: 0.36 5Hz: 0.09
    frame_id: laser_link      # Point cloud frame ID
    topic_name: lslidar_point_cloud # Point cloud topic name
    publish_scan: false       # Whether to publish laserscan topic
    scan_num: 8               # Laserscan line number
    coordinate_opt: false     # Point cloud 0 degree angle corresponding direction true: x-axis positive direction
    #pcap: /home/ls/Downloads/xxx.pcap   # PCAP file path, open this comment when parsing PCAP file offline
