ekf_filter_node:
  frequency: 30
  sensor_timeout: 0.2
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.1
  map_frame: map
  odom_frame: odom
  base_link_frame: base_footprint
  world_frame: odom

  # IMU data
  imu0: /imu
  imu0_config: [false, false, false,    # X, Y, Z positions (not used)
              false, false, true,     # Use only yaw (ignore roll and pitch)
              false, false, false,    # Ignore linear velocities
              false, false, true]     # Use only yaw angular velocity (ignore others)

  imu0_differential: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

  # # Laser scan data
  # laser_scan0: /scan  # Replace with your actual laser scan topic
  # laser_scan0_config: [true, true, false,  # X, Y
  #                      false, false, false, # Z, Roll, Pitch
  #                      false, false, true,  # Yaw, Linear Velocity X, Y
  #                      false, false, false] # Angular Velocity Z
  # laser_scan0_differential: false
  # laser_scan0_queue_size: 10

  # # Noise covariances
  # process_noise_covariance: [0.1, 0, 0, 0, 0, 0,
  #                            0, 0.1, 0, 0, 0, 0,
  #                            0, 0, 0.05, 0, 0, 0,
  #                            0, 0, 0, 0.05, 0, 0,
  #                            0, 0, 0, 0, 0.05, 0,
  #                            0, 0, 0, 0, 0, 0.05]

  # initial_estimate_covariance: [0.5, 0, 0, 0, 0, 0,
  #                               0, 0.5, 0, 0, 0, 0,
  #                               0, 0, 0.1, 0, 0, 0,
  #                               0, 0, 0, 0.1, 0, 0,
  #                               0, 0, 0, 0, 0.1, 0,
  #                               0, 0, 0, 0, 0, 0.1]
