controller_manager:
  ros__parameters:
    update_rate: 30.0
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 30.0
    base_frame_id: base_footprint

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.77 # ${mobile_w - leg_w} # ${0.85 - 0.08}
    wheel_radius: 0.16 # ${wheel_radius}  # wheel_radius = 0.16

    use_stamped_vel: false




# diff_drive_controller:       #diff_drive_controller 
#   ros__parameters:

#     base_frame_id: mobile_base_footprint

#     left_wheel_names: ["left_wheel_joint"]
#     right_wheel_names: ["right_wheel_joint"]
#     wheel_separation: 0.77 #${mobile_w - leg_w} #${0.85 - 0.08}
#     wheel_radius: 0.16 #${wheel_radius}  #wheel_radius = 0.16

#     use_stamped_vel: false #articulated video
#     #cmd_vel_timeout: 0.5
#     publish_rate: 100


